# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

powerSparseProduct <- function(mRe1, mIm1, mRe2, mIm2) {
    .Call('powerr_powerSparseProduct', PACKAGE = 'powerr', mRe1, mIm1, mRe2, mIm2)
}

rcppeigen_hello_world <- function() {
    .Call('powerr_rcppeigen_hello_world', PACKAGE = 'powerr')
}

rcppeigen_outerproduct <- function(x) {
    .Call('powerr_rcppeigen_outerproduct', PACKAGE = 'powerr', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('powerr_rcppeigen_innerproduct', PACKAGE = 'powerr', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('powerr_rcppeigen_bothproducts', PACKAGE = 'powerr', x)
}

