# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' powerSparseProduct
#' 
#' use C++ to calculate matrix product between sparse martix including complex numbers
#' 
#' @param mRe1 real part of first sparse matrix
#' @param mIm1 imagine part of first sparse matrix
#' @param mRe2 real part of second sparse matrix
#' @param mIm2 imagine part of second sparse matrix
powerSparseProduct <- function(mRe1, mIm1, mRe2, mIm2) {
    .Call('powerr_powerSparseProduct', PACKAGE = 'powerr', mRe1, mIm1, mRe2, mIm2)
}

